/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ConnectionBD;
import control.Querys;
import java.awt.Color;
import java.util.ArrayList;
import model.Client;

/**
 *
 * @author Onion
 */
public class graphicInterface extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public graphicInterface() {
        m = new mainPanel();
        s = new seeRows();
        n = new newRowPanel();
        l = new logInPanel();
     
        initComponents();
           a = new aboutOfPanel();
        ConnectionBD.Connect();
        setResizable(false);
                

    }

  

    public static void showSeeRowsPanel() {
        gui.add(s);
        gui.setContentPane(s);
        gui.pack();
    }

    public void showMainPanel() {
        gui.add(m);
        gui.setContentPane(m);
        gui.pack();
        
        if(!isLoged){
            username = l.getUsername();
            password = l.getPassword();
        }
            
        
        isLoged = true;
        System.out.println(isLoged);
    }

    public static String getUsername() {
        return username;
    }

    public static String getPassword() {
        return password;
    }

    public static void showAboutOfPanel() {
        gui.add(a);
        gui.setContentPane(a);
        gui.pack();
    }

    public static void showLoginPanel() {

        gui.add(l);
        gui.setContentPane(l);
        gui.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        labelMainTitle = new javax.swing.JLabel();
        labelAuthor = new javax.swing.JLabel();
        aboutOfPanel = new javax.swing.JPanel();
        labelParagraph = new javax.swing.JLabel();
        buttonVisitGithub = new javax.swing.JButton();
        labelParagraph2 = new javax.swing.JLabel();
        labelParagraph3 = new javax.swing.JLabel();
        labelParagraph4 = new javax.swing.JLabel();
        labelParagraph5 = new javax.swing.JLabel();
        labelParagraph7 = new javax.swing.JLabel();
        labelParagraph6 = new javax.swing.JLabel();
        labelParagrap8 = new javax.swing.JLabel();
        logInPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        loginTitle = new javax.swing.JLabel();
        psswdLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        usernameField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        logInButton = new javax.swing.JButton();
        menuMainBar = new javax.swing.JMenuBar();
        mainMenuItem = new javax.swing.JMenu();
        aboutOfItem = new javax.swing.JMenu();
        seeRowsItem = new javax.swing.JMenu();
        newRowItem = new javax.swing.JMenu();
        propertiesItem = new javax.swing.JMenu();
        logOutItem = new javax.swing.JMenu();

        mainPanel.setPreferredSize(new java.awt.Dimension(720, 564));

        labelMainTitle.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        labelMainTitle.setForeground(new java.awt.Color(236, 243, 246));
        labelMainTitle.setText("      Rubiel Gym's Management App");

        labelAuthor.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        labelAuthor.setForeground(new java.awt.Color(236, 243, 246));
        labelAuthor.setText("Developed by: Antonio Carrasco García");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAuthor)
                .addContainerGap(471, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelMainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(502, Short.MAX_VALUE)
                .addComponent(labelAuthor)
                .addGap(47, 47, 47))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(labelMainTitle)
                    .addContainerGap(493, Short.MAX_VALUE)))
        );

        aboutOfPanel.setPreferredSize(new java.awt.Dimension(720, 564));

        labelParagraph.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        labelParagraph.setForeground(new java.awt.Color(236, 243, 246));
        labelParagraph.setText("This application was developed on NetBeans 12.3.");

        labelParagraph2.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        labelParagraph2.setForeground(new java.awt.Color(236, 243, 246));
        labelParagraph2.setText("About Of");

        labelParagraph3.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        labelParagraph3.setForeground(new java.awt.Color(236, 243, 246));
        labelParagraph3.setText("The database used on this application was derby");

        labelParagraph4.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        labelParagraph4.setForeground(new java.awt.Color(236, 243, 246));
        labelParagraph4.setText("If you want to contact me, you can send me an e-mail ");

        labelParagraph5.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        labelParagraph5.setForeground(new java.awt.Color(236, 243, 246));
        labelParagraph5.setText("acargar1002@g.educaand.es");

        labelParagraph7.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        labelParagraph7.setForeground(new java.awt.Color(236, 243, 246));
        labelParagraph7.setText("I have an account on github also, if you want to see ");

        labelParagraph6.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        labelParagraph6.setForeground(new java.awt.Color(236, 243, 246));
        labelParagraph6.setText("my repositories and projects, click the following button");

        labelParagrap8.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        labelParagrap8.setForeground(new java.awt.Color(236, 243, 246));
        labelParagrap8.setText("at the following e-mail address");

        javax.swing.GroupLayout aboutOfPanelLayout = new javax.swing.GroupLayout(aboutOfPanel);
        aboutOfPanel.setLayout(aboutOfPanelLayout);
        aboutOfPanelLayout.setHorizontalGroup(
            aboutOfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutOfPanelLayout.createSequentialGroup()
                .addGroup(aboutOfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutOfPanelLayout.createSequentialGroup()
                        .addGroup(aboutOfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aboutOfPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelParagraph))
                            .addGroup(aboutOfPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelParagraph3))
                            .addGroup(aboutOfPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelParagraph7))
                            .addGroup(aboutOfPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelParagraph6)))
                        .addGap(0, 170, Short.MAX_VALUE))
                    .addGroup(aboutOfPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(aboutOfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelParagraph4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(aboutOfPanelLayout.createSequentialGroup()
                                .addComponent(labelParagrap8)
                                .addGap(55, 55, 55)
                                .addComponent(labelParagraph5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutOfPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(aboutOfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutOfPanelLayout.createSequentialGroup()
                        .addComponent(labelParagraph2)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutOfPanelLayout.createSequentialGroup()
                        .addComponent(buttonVisitGithub, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285))))
        );
        aboutOfPanelLayout.setVerticalGroup(
            aboutOfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutOfPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelParagraph2)
                .addGap(43, 43, 43)
                .addComponent(labelParagraph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelParagraph3)
                .addGap(50, 50, 50)
                .addComponent(labelParagraph4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutOfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelParagrap8)
                    .addComponent(labelParagraph5))
                .addGap(55, 55, 55)
                .addComponent(labelParagraph7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelParagraph6)
                .addGap(33, 33, 33)
                .addComponent(buttonVisitGithub, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        logInPanel.setPreferredSize(new java.awt.Dimension(720, 564));

        usernameLabel.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(236, 243, 246));
        usernameLabel.setText("Username");

        loginTitle.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        loginTitle.setForeground(new java.awt.Color(236, 243, 246));
        loginTitle.setText("Log In");

        psswdLabel.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        psswdLabel.setForeground(new java.awt.Color(236, 243, 246));
        psswdLabel.setText("Password");

        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setText("jPasswordField1");
        passwordField.setCaretColor(new java.awt.Color(197, 199, 202));
        passwordField.setPreferredSize(new java.awt.Dimension(250, 34));

        usernameField.setForeground(new java.awt.Color(255, 255, 255));
        usernameField.setCaretColor(new java.awt.Color(197, 199, 202));
        usernameField.setPreferredSize(new java.awt.Dimension(250, 34));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        logInButton.setForeground(new java.awt.Color(236, 243, 246));
        logInButton.setText("Log in");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logInPanelLayout = new javax.swing.GroupLayout(logInPanel);
        logInPanel.setLayout(logInPanelLayout);
        logInPanelLayout.setHorizontalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginTitle)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(logInButton)
                        .addGroup(logInPanelLayout.createSequentialGroup()
                            .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(psswdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(351, Short.MAX_VALUE))
        );
        logInPanelLayout.setVerticalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(loginTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(18, 18, 18)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psswdLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainMenuItem.setText("Main menu     ");
        mainMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMenuItemMouseClicked(evt);
            }
        });
        menuMainBar.add(mainMenuItem);

        aboutOfItem.setText("About of      ");
        aboutOfItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutOfItemMouseClicked(evt);
            }
        });
        aboutOfItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutOfItemActionPerformed(evt);
            }
        });
        menuMainBar.add(aboutOfItem);

        seeRowsItem.setText("See info      ");
        seeRowsItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeRowsItemMouseClicked(evt);
            }
        });
        menuMainBar.add(seeRowsItem);

        newRowItem.setText("New Row      ");
        newRowItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newRowItemMouseClicked(evt);
            }
        });
        newRowItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRowItemActionPerformed(evt);
            }
        });
        menuMainBar.add(newRowItem);

        propertiesItem.setText("Properties      ");
        propertiesItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                propertiesItemMouseClicked(evt);
            }
        });
        menuMainBar.add(propertiesItem);

        logOutItem.setText("Log out");
        logOutItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutItemMouseClicked(evt);
            }
        });
        menuMainBar.add(logOutItem);

        setJMenuBar(menuMainBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logInButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void buttonVisitGithubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVisitGithubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVisitGithubActionPerformed

    private void aboutOfItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutOfItemMouseClicked
        // TODO add your handling code here:
        if(isLoged)
            showAboutOfPanel();
    }//GEN-LAST:event_aboutOfItemMouseClicked

    private void mainMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuItemMouseClicked
        // TODO add your handling code here:
        
        if(isLoged)
             showMainPanel();
    }//GEN-LAST:event_mainMenuItemMouseClicked

    private void seeRowsItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeRowsItemMouseClicked
        // TODO add your handling code here:
        if(isLoged)
            showSeeRowsPanel();
    }//GEN-LAST:event_seeRowsItemMouseClicked

    private void newRowItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newRowItemMouseClicked
        if(isLoged)
            showNewRowPanel();

    }//GEN-LAST:event_newRowItemMouseClicked

    public static void showNewRowPanel() {
        // TODO add your handling code here:

        gui.add(n);
        gui.setContentPane(n);
        gui.pack();
    }

    private void propertiesItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propertiesItemMouseClicked
        if(isLoged){
            p = new propertiesPanel();
            showPropertiesPanel();
        }
    }//GEN-LAST:event_propertiesItemMouseClicked

    public static void showPropertiesPanel() {
        // TODO add your handling code here:

        gui.add(p);
        gui.setContentPane(p);
        gui.pack();
    }

    private void logOutItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutItemMouseClicked
        
       
        isLoged = false;
        showLoginPanel();
        
    }//GEN-LAST:event_logOutItemMouseClicked

    private void newRowItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRowItemActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_newRowItemActionPerformed

    private void aboutOfItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutOfItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutOfItemActionPerformed

    /**
     * @param args the command line arguments
     */
    static graphicInterface gui;

    public static void main(String args[]) {

        gui = new graphicInterface();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gui.setVisible(true);
                
            }
        });

        
       graphicInterface.showLoginPanel();
       
       
           

    }
    
    private static String username;
    private static String password;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutOfItem;
    private javax.swing.JPanel aboutOfPanel;
    private javax.swing.JButton buttonVisitGithub;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAuthor;
    private javax.swing.JLabel labelMainTitle;
    private javax.swing.JLabel labelParagrap8;
    private javax.swing.JLabel labelParagraph;
    private javax.swing.JLabel labelParagraph2;
    private javax.swing.JLabel labelParagraph3;
    private javax.swing.JLabel labelParagraph4;
    private javax.swing.JLabel labelParagraph5;
    private javax.swing.JLabel labelParagraph6;
    private javax.swing.JLabel labelParagraph7;
    private javax.swing.JButton logInButton;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JMenu logOutItem;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JMenu mainMenuItem;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuMainBar;
    private javax.swing.JMenu newRowItem;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JMenu propertiesItem;
    private javax.swing.JLabel psswdLabel;
    private javax.swing.JMenu seeRowsItem;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    //Colors used on this app
    Color panelBackground = new java.awt.Color(46, 70, 120);
    Color textFieldBackground = new java.awt.Color(129, 143, 173);
    Color buttonBackground = new java.awt.Color(80, 112, 170);

    //Panels
    static logInPanel l;
    static aboutOfPanel a;
    static mainPanel m;
    static seeRows s;
    static newRowPanel n;
    static propertiesPanel p;

    static boolean isLoged;

}
