/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;

/**
 *
 * @author Onion
 */
public class mainPanel extends javax.swing.JPanel {

    /**
     * Creates new form mainPanel
     */
    public mainPanel() {
        initComponents();
        
        setBackground(panelBackground);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMainTitle = new javax.swing.JLabel();
        labelAuthor = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(720, 560));

        labelMainTitle.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        labelMainTitle.setForeground(new java.awt.Color(236, 243, 246));
        labelMainTitle.setText("Rubiel's Gym management app");

        labelAuthor.setFont(new java.awt.Font("Sitka Small", 0, 17)); // NOI18N
        labelAuthor.setForeground(new java.awt.Color(236, 243, 246));
        labelAuthor.setText("Developed by: Antonio Carrasco García");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelMainTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, Short.MAX_VALUE)
                .addComponent(labelAuthor)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    Color panelBackground = new java.awt.Color(46,70,120);
    Color textFieldBackground = new java.awt.Color(129,143,173);
    Color buttonBackground = new java.awt.Color(80, 112, 170);
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAuthor;
    private javax.swing.JLabel labelMainTitle;
    // End of variables declaration//GEN-END:variables
}
