/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Insert;
import control.Querys;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Client;
import model.TrainingPlan;

/**
 *
 * @author Onio
 */
public class newRowPanel extends javax.swing.JPanel {

    /**
     * Creates new form newRowPanel
     */
    
    private static ArrayList<Client> clientQuery = new ArrayList();
    private static ArrayList<TrainingPlan> trainingPlanQuery = new ArrayList();
    
    public newRowPanel() {
        
        initComponents();
        setTheme();
        
       
        

    }
    
    DefaultListModel defLisMod = new DefaultListModel();
    DefaultListModel defLisMod2 = new DefaultListModel();
    
    
    public void setTheme() {
        setBackground(panelBackground);
        
        applyButton.setBackground(buttonBackground);
        clearButton.setBackground(buttonBackground);
        
        clientCodeTextField.setBackground(textFieldBackground);
        codeTextField.setBackground(textFieldBackground);
        trainingPlanCodeTextField.setBackground(textFieldBackground);
        
        showCodeButton.setBackground(buttonBackground);
        clientCodeList.setBackground(textFieldBackground);
        trainingPlanCodeList.setBackground(textFieldBackground);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        applyButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        codeTextField = new javax.swing.JTextField();
        trainingPlanCodeTextField = new javax.swing.JTextField();
        clientCodeTextField = new javax.swing.JTextField();
        codeLabel = new javax.swing.JLabel();
        clientCodeLabel = new javax.swing.JLabel();
        trainingPlanCodeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientCodeList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        trainingPlanCodeList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        showCodeButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 243, 246));
        jLabel1.setText("Do a new pay");

        applyButton.setForeground(new java.awt.Color(236, 243, 246));
        applyButton.setText("Apply");
        applyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applyButtonMouseClicked(evt);
            }
        });
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        clearButton.setForeground(new java.awt.Color(236, 243, 246));
        clearButton.setText("Clear");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        codeTextField.setEditable(false);
        codeTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        codeTextField.setForeground(new java.awt.Color(255, 255, 255));

        trainingPlanCodeTextField.setEditable(false);
        trainingPlanCodeTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        trainingPlanCodeTextField.setForeground(new java.awt.Color(255, 255, 255));

        clientCodeTextField.setEditable(false);
        clientCodeTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clientCodeTextField.setForeground(new java.awt.Color(255, 255, 255));

        codeLabel.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        codeLabel.setForeground(new java.awt.Color(236, 243, 246));
        codeLabel.setText("Code");

        clientCodeLabel.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        clientCodeLabel.setForeground(new java.awt.Color(236, 243, 246));
        clientCodeLabel.setText("Client code");

        trainingPlanCodeLabel.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        trainingPlanCodeLabel.setForeground(new java.awt.Color(236, 243, 246));
        trainingPlanCodeLabel.setText("Training plan code");

        clientCodeList.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        clientCodeList.setForeground(new java.awt.Color(255, 255, 255));
        clientCodeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientCodeListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clientCodeList);

        trainingPlanCodeList.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        trainingPlanCodeList.setForeground(new java.awt.Color(255, 255, 255));
        trainingPlanCodeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trainingPlanCodeListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(trainingPlanCodeList);

        jLabel2.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Client codes available");

        jLabel3.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Training plan codes available");

        showCodeButton.setForeground(new java.awt.Color(236, 243, 246));
        showCodeButton.setText("Show codes");
        showCodeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showCodeButtonMouseClicked(evt);
            }
        });
        showCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCodeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(codeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(clientCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clientCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(codeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(trainingPlanCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(trainingPlanCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(showCodeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(showCodeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainingPlanCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trainingPlanCodeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applyButton)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applyButtonActionPerformed

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        // TODO add your handling code here:
        trainingPlanCodeTextField.setText("");
        clientCodeTextField.setText("");
        codeTextField.setText("");
    }//GEN-LAST:event_clearButtonMouseClicked

    private void showCodeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showCodeButtonMouseClicked
        // TODO add your handling code here:
        String queryTrainingPlan = "SELECT TRAINING_PLAN_COD FROM TRAININGPLAN";
        trainingPlanCodeList.setModel(defLisMod);
        
        ArrayList<String> codes = new ArrayList();
        codes = Querys.codesAvailables(queryTrainingPlan);
        
        for(String e: codes){
            defLisMod.addElement(e);
        }
        
        
        String queryClient = "SELECT CLIENT_COD FROM CLIENT";
        clientCodeList.setModel(defLisMod2);
        
        codes = new ArrayList();
        codes = Querys.codesAvailables(queryClient);
        
        
        for(String e: codes){
            defLisMod2.addElement(e);
        }
        
        showCodeButton.setEnabled(false);
        showCodeButton.setVisible(false);
        
    }//GEN-LAST:event_showCodeButtonMouseClicked

    private void clientCodeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientCodeListMouseClicked
        // TODO add your handling code here:
        
        clientCodeTextField.setText(clientCodeList.getSelectedValue());
      
    }//GEN-LAST:event_clientCodeListMouseClicked

    private void trainingPlanCodeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainingPlanCodeListMouseClicked
        // TODO add your handling code here:
        trainingPlanCodeTextField.setText(trainingPlanCodeList.getSelectedValue());
    }//GEN-LAST:event_trainingPlanCodeListMouseClicked

    private void showCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCodeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showCodeButtonActionPerformed

    private void applyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyButtonMouseClicked
        // TODO add your handling code here:
        
        if (trainingPlanCodeTextField.getText().length() != 0 && clientCodeTextField.getText().length() != 0) {
            int paycod = 0;
            int trainingPlanCod = Integer.parseInt(trainingPlanCodeTextField.getText());
            int clientCod = Integer.parseInt(clientCodeTextField.getText());
            String query = "SELECT COUNT(*) FROM MONTHLYPAYMENT WHERE TRAINING_PLAN_COD = ? AND CLIENT_COD = ?";
            paycod = Querys.queryGenerateNewPaymentId(query, trainingPlanCod, clientCod);
            paycod++;
            codeTextField.setText("" + paycod);
            int payment = 0;
            int clientAge = 0;
            query = "SELECT AGE FROM CLIENT WHERE CLIENT_COD = ?";
            clientAge = Querys.queryGetClientAge(query, clientCod);
            query = "SELECT PRICE_MONTH FROM TRAININGPLAN WHERE TRAINING_PLAN_COD = ?";
            int priceMonth = Querys.queryGetPriceMonthTrainingPlan(query, trainingPlanCod);

            if (clientAge > 15 && clientAge < 30) { // 16 - 29
                payment = priceMonth / 2;
            } else if (clientAge >= 30 && clientAge < 46) { //30 - 45
                payment = priceMonth - (40 * priceMonth / 100);
            } else if (clientAge > 45) { // > 45
                payment = priceMonth - (30 * priceMonth / 100);
            }
            String insert = "INSERT INTO MONTHLYPAYMENT VALUES (" + paycod + "," + clientCod + "," + trainingPlanCod + "," + payment + ")";
            Insert.insertInto(insert);
            Window.showMessage("INSERT HAS BEEN MADE WITHOUT PROBLEMS\nPay Code: " + paycod + " Client code: " + clientCod + "\nTraining Plan Code: " + trainingPlanCod + "Payment: " + payment);
        } else {
            Window.showMessage("Error: Training Plan Code and Client Code must have a value, try again");
        }

    }//GEN-LAST:event_applyButtonMouseClicked
    
    Color panelBackground = new java.awt.Color(46, 70, 120);
    Color textFieldBackground = new java.awt.Color(129, 143, 173);
    Color buttonBackground = new java.awt.Color(80, 112, 170);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel clientCodeLabel;
    private javax.swing.JList<String> clientCodeList;
    private javax.swing.JTextField clientCodeTextField;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JTextField codeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton showCodeButton;
    private javax.swing.JLabel trainingPlanCodeLabel;
    private javax.swing.JList<String> trainingPlanCodeList;
    private javax.swing.JTextField trainingPlanCodeTextField;
    // End of variables declaration//GEN-END:variables
}
