/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.aeat.valida.Validador;
import control.Delete;
import control.ExceptionError;
import control.FileCopy;
import control.Insert;

import control.Querys;
import control.Update;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import model.Trainer;

/**
 *
 * @author Onio
 */
public class propertiesPanel extends javax.swing.JPanel {

    /**
     * Creates new form propertiesPanel
     */
    private static Trainer t;
    private static ExceptionError e = new ExceptionError();
        ;
    
    public propertiesPanel() {
        initComponents();

        File currentDir = new File("./images/");
        jFileChooser1.setCurrentDirectory(currentDir);

        String query = "SELECT * FROM TRAINER WHERE USERNAME = ? AND PASSWORD = ?";

        t = Querys.queryReturnTrainerInfo(query, graphicInterface.getUsername(), graphicInterface.getPassword());

        usernameTextField.setText(t.getUsername());
        passwordTextField.setText(t.getPassword());

        
        Image img = new ImageIcon("./images/" + t.getPhotoTitle()).getImage();
        ImageIcon img2 = new ImageIcon(img.getScaledInstance(132, 132, Image.SCALE_SMOOTH));
        jLabel3.setIcon(img2);

        int month = t.getDischargeDate().getMonth();
        
        if(month != 12)
            month++;

        
        

        
        dischargeDateTextField.setText("" + t.getDischargeDate().getYear() + "-" + month + "-" + t.getDischargeDate().getDate());
        nidTextField.setText(t.getNID());

        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_ONLY);

        previousDNI = t.getNID();

        

        setTheme();

    }

    private static String previousDNI;

    public void setTheme() {
        setBackground(panelBackground);
        passwordTextField.setBackground(textFieldBackground);
        nidTextField.setBackground(textFieldBackground);
        dischargeDateTextField.setBackground(textFieldBackground);
        usernameTextField.setBackground(textFieldBackground);
        saveButton.setBackground(buttonBackground);
        jButton1.setBackground(buttonBackground);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        usernameLabel = new javax.swing.JLabel();
        passwordLabelñ = new javax.swing.JLabel();
        nidLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        dischargeDateLabel = new javax.swing.JLabel();
        nidTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        dischargeDateTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(720, 560));

        jLabel1.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 243, 246));
        jLabel1.setText("Trainer info");

        usernameLabel.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(236, 243, 246));
        usernameLabel.setText("Username");

        passwordLabelñ.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        passwordLabelñ.setForeground(new java.awt.Color(236, 243, 246));
        passwordLabelñ.setText("Password");

        nidLabel.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        nidLabel.setForeground(new java.awt.Color(236, 243, 246));
        nidLabel.setText("NID");

        photoLabel.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        photoLabel.setForeground(new java.awt.Color(236, 243, 246));
        photoLabel.setText("Photo");

        dischargeDateLabel.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        dischargeDateLabel.setForeground(new java.awt.Color(236, 243, 246));
        dischargeDateLabel.setText("Discharge date");

        nidTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nidTextField.setForeground(new java.awt.Color(255, 255, 255));

        passwordTextField.setEditable(false);
        passwordTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordTextField.setForeground(new java.awt.Color(255, 255, 255));

        usernameTextField.setEditable(false);
        usernameTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usernameTextField.setForeground(new java.awt.Color(255, 255, 255));

        dischargeDateTextField.setEditable(false);
        dischargeDateTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dischargeDateTextField.setForeground(new java.awt.Color(255, 255, 255));

        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\Program Files\\NetBeans-12.3\\.\\images"));
        jFileChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFileChooser1MouseClicked(evt);
            }
        });
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 243, 246));
        jLabel2.setText("Select a date");

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Apply");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(saveButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usernameLabel)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(passwordLabelñ)
                                            .addComponent(nidLabel)))
                                    .addGap(72, 72, 72)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dischargeDateLabel)
                                    .addComponent(photoLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dischargeDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(usernameLabel)
                                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dischargeDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dischargeDateLabel))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(photoLabel)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nidLabel)
                            .addComponent(nidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(passwordLabelñ))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addComponent(saveButton)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 38, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private static String title;


    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:

        String s;
        s = jFileChooser1.getSelectedFile().getPath();

        String path = "./" + s.substring(s.indexOf("images"));
        if (path.contains("\\")) {
            path = path.replace('\\', '/');
        }

        String fileName = path.substring(9);

        title = fileName;
        Image img = new ImageIcon(path).getImage();
        ImageIcon img2 = new ImageIcon(img.getScaledInstance(132, 132, Image.SCALE_SMOOTH));
        jLabel3.setIcon(img2);
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        int year, month, day;
        String[] sdStructure = new String[3];
        int currentYear, currentMonth, currentDay;

        boolean goodDate;

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDateTime now = LocalDateTime.now();

        String currentDate = dtf.format(now);

        sdStructure = currentDate.split("-");
        currentYear = Integer.parseInt(sdStructure[0]);
        currentMonth = Integer.parseInt(sdStructure[1]);
        currentDay = Integer.parseInt(sdStructure[2]);

        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String sd = dateFormat.format(jDateChooser2.getDate());

            sdStructure = sd.split("-");

            year = Integer.parseInt(sdStructure[0]);
            month = Integer.parseInt(sdStructure[1]);
            day = Integer.parseInt(sdStructure[2]);

            if (year > currentYear) {
                goodDate = false;
            } else if (year == currentYear && month > currentMonth) {
                goodDate = false;
            } else if (year == currentYear && month == currentMonth && day > currentDay) {
                goodDate = false;
            } else {
                goodDate = true;
            }

            try {
                validateDate(goodDate, sd);
            } catch (ExceptionError ex) {
                ex.dateGreaterThanCurrentDate(currentDate,800);
            }

        } catch (NullPointerException npe) {
           e.emptyDate(600);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    public void validateDate(boolean goodDate, String sd) throws ExceptionError{
        if (goodDate) {
            dischargeDateTextField.setText(sd);
        } else {
            
            throw e;
            
        }
    }

    private void jFileChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFileChooser1MouseClicked
        // TODO add your handling code here:

        File f = jFileChooser1.getSelectedFile();

        System.out.println(f);

    }//GEN-LAST:event_jFileChooser1MouseClicked

    //ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT FOREIGN KEY (NID) REFERENCES TRAINER ON DELETE CASCADE;
    //ALTER TABLE CLIENT DROP CONSTRAINT FK_CLIENT;

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        // TODO add your handling code here:
        Validador val = new Validador();

        int correcto = val.vNif(nidTextField.getText());
        
        String tf = nidTextField.getText();

        try {
            validateNID(correcto, tf);
        } catch (ExceptionError ex) {
            e.NIDNotValid(700);
        }


    }//GEN-LAST:event_saveButtonMouseClicked

    public void validateNID(int correcto, String tf) throws ExceptionError {
        if (correcto > 0) {
            
            String query;
            
            int rows = 0;
            
            
            tf = tf.replace(" ", "");
            previousDNI = previousDNI.replace(" ", "");
            
            if (!previousDNI.equals(tf)){
                query = "SELECT COUNT(*) FROM TRAINER WHERE NID = ?";
                rows = Querys.queryCheckNidTrainer(query, nidTextField.getText());
            }
            
            try {
                checkInsertOrUpdate(rows, tf);
            } catch (ExceptionError ex) {
                e.repeatedNID(500);
            }
            
        } else {
            throw e;
        }
    }

    public void checkInsertOrUpdate(int rows, String tf)throws ExceptionError {
        String query;
        if (rows != 0 ) {
            throw e;
        } else {
            
            
            if(!previousDNI.equals(tf)){
                
                //Insertamos un entrenador temporal
                String insert = "INSERT INTO TRAINER VALUES ( NULL,'" + nidTextField.getText()+"','DELETE','DELETE',NULL)";
                Insert.insertInto(insert);
                
                
                //Updateamos las FK de cliente
                query = "UPDATE CLIENT SET NID = ? WHERE NID = ?";
                Update.updateClients(query, nidTextField.getText(), previousDNI);
                
                //Una vez actualizadas las FK, borramos el entrenador anterior
                String delete = "DELETE FROM TRAINER WHERE NID = '"+previousDNI+"'";
                Delete.deleteElement(delete);
                
                
                //Hacemos update
                String update = "UPDATE TRAINER SET USERNAME ='"+usernameTextField.getText()+"', PASSWORD = '" +passwordTextField.getText()+"' ,  NID = '"+nidTextField.getText()+"' , PHOTO_TITLE = '"+title+"' , DISCHARGE_DATE = '"+dischargeDateTextField.getText()+"'"
                        + "WHERE NID = '"+nidTextField.getText()+"'";
                
                Update.updateOrder(update);
                
                previousDNI = nidTextField.getText();
                
            }else{
                
                
                query = "UPDATE TRAINER SET DISCHARGE_DATE = '"+dischargeDateTextField.getText()+"', PHOTO_TITLE = '"+title+"' , USERNAME ='"+usernameTextField.getText()+"', PASSWORD = '" +passwordTextField.getText()+"' WHERE NID = '"+nidTextField.getText()+"'";
                
                Update.updateOrder(query);
                
            }
        }
    }
    Color panelBackground = new java.awt.Color(46, 70, 120);
    Color textFieldBackground = new java.awt.Color(129, 143, 173);
    Color buttonBackground = new java.awt.Color(80, 112, 170);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dischargeDateLabel;
    private javax.swing.JTextField dischargeDateTextField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nidLabel;
    private javax.swing.JTextField nidTextField;
    private javax.swing.JLabel passwordLabelñ;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
