/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ClientQuery;
import control.ExceptionError;
import control.Querys;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Client;
import model.Pay;

/**
 *
 * @author Onion
 */
public class seeRows extends javax.swing.JPanel {

    private boolean clickedIntoPayInfo = false;

    public boolean isClickedIntoPayInfo() {
        return clickedIntoPayInfo;
    }

    public void setClickedIntoPayInfo(boolean clickedIntoPayInfo) {
        this.clickedIntoPayInfo = clickedIntoPayInfo;
    }

    /**
     * Creates new form seeRows
     */
    public seeRows() {
        initComponents();
        buttonSeePayInfo.setEnabled(false);
        buttonReturn.show(false);
        buttonFirst.setEnabled(false);
        buttonLast.setEnabled(false);
        buttonFirst.setVisible(false);
        buttonLast.setVisible(false);
        setTheme();
        payPanel.show(false);
        firstTime = true;

    }

    public void setTheme() {
        clientCodeTextField.setBackground(textFieldBackground);
        clientAgeTextField.setBackground(textFieldBackground);
        clientNameTextField.setBackground(textFieldBackground);
        clientDateTextField.setBackground(textFieldBackground);
        trainerNIFTextField.setBackground(textFieldBackground);
        setBackground(panelBackground);
        buttonSeePayInfo.setBackground(buttonBackground);
        buttonBack.setBackground(buttonBackground);
        buttonFirst.setBackground(buttonBackground);
        buttonNext.setBackground(buttonBackground);
        buttonLast.setBackground(buttonBackground);
        payPanel.setBackground(textFieldBackground);
        payList.setBackground(textFieldBackground);
        buttonReturn.setBackground(buttonBackground);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        separatorTitle = new javax.swing.JSeparator();
        clientCodeTextField = new javax.swing.JTextField();
        clientNameTextField = new javax.swing.JTextField();
        clientAgeTextField = new javax.swing.JTextField();
        clientDateTextField = new javax.swing.JTextField();
        trainerNIFTextField = new javax.swing.JTextField();
        labelClientCode = new javax.swing.JLabel();
        labelClientAge = new javax.swing.JLabel();
        labelClientName = new javax.swing.JLabel();
        labelTrainerNIF = new javax.swing.JLabel();
        labelClientDate = new javax.swing.JLabel();
        buttonNext = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        buttonFirst = new javax.swing.JButton();
        buttonLast = new javax.swing.JButton();
        buttonSeePayInfo = new javax.swing.JButton();
        payPanel = new javax.swing.JScrollPane();
        payList = new javax.swing.JList<>();
        buttonReturn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(720, 560));

        titleLabel.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(236, 243, 246));
        titleLabel.setText("Query Client");

        clientCodeTextField.setEditable(false);
        clientCodeTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clientCodeTextField.setForeground(new java.awt.Color(255, 255, 255));

        clientNameTextField.setEditable(false);
        clientNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clientNameTextField.setForeground(new java.awt.Color(255, 255, 255));

        clientAgeTextField.setEditable(false);
        clientAgeTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clientAgeTextField.setForeground(new java.awt.Color(255, 255, 255));

        clientDateTextField.setEditable(false);
        clientDateTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clientDateTextField.setForeground(new java.awt.Color(255, 255, 255));

        trainerNIFTextField.setEditable(false);
        trainerNIFTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        trainerNIFTextField.setForeground(new java.awt.Color(255, 255, 255));

        labelClientCode.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        labelClientCode.setForeground(new java.awt.Color(236, 243, 246));
        labelClientCode.setText("Client Code");

        labelClientAge.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        labelClientAge.setForeground(new java.awt.Color(236, 243, 246));
        labelClientAge.setText("Client Age");

        labelClientName.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        labelClientName.setForeground(new java.awt.Color(236, 243, 246));
        labelClientName.setText("Client Name");

        labelTrainerNIF.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        labelTrainerNIF.setForeground(new java.awt.Color(236, 243, 246));
        labelTrainerNIF.setText("Trainer NIF");

        labelClientDate.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        labelClientDate.setForeground(new java.awt.Color(236, 243, 246));
        labelClientDate.setText("Discharge date");

        buttonNext.setForeground(new java.awt.Color(255, 255, 255));
        buttonNext.setText("Next");
        buttonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNextMouseClicked(evt);
            }
        });
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        buttonBack.setForeground(new java.awt.Color(255, 255, 255));
        buttonBack.setText("Back");
        buttonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBackMouseClicked(evt);
            }
        });

        buttonFirst.setForeground(new java.awt.Color(255, 255, 255));
        buttonFirst.setText("First");
        buttonFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFirstMouseClicked(evt);
            }
        });

        buttonLast.setForeground(new java.awt.Color(255, 255, 255));
        buttonLast.setText("Last");
        buttonLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLastMouseClicked(evt);
            }
        });

        buttonSeePayInfo.setForeground(new java.awt.Color(255, 255, 255));
        buttonSeePayInfo.setText("See pay info");
        buttonSeePayInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSeePayInfoMouseClicked(evt);
            }
        });
        buttonSeePayInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeePayInfoActionPerformed(evt);
            }
        });

        payList.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        payList.setForeground(new java.awt.Color(255, 255, 255));
        payPanel.setViewportView(payList);

        buttonReturn.setForeground(new java.awt.Color(255, 255, 255));
        buttonReturn.setText("Return");
        buttonReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonReturnMouseClicked(evt);
            }
        });
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(separatorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(349, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonSeePayInfo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelClientDate)
                                    .addComponent(labelClientAge)
                                    .addComponent(labelClientName)
                                    .addComponent(labelClientCode)
                                    .addComponent(buttonBack)
                                    .addComponent(labelTrainerNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clientCodeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trainerNIFTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientDateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientAgeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(buttonFirst)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonLast)
                                        .addGap(159, 159, 159)
                                        .addComponent(buttonNext)))))
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonReturn)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(24, Short.MAX_VALUE)
                    .addComponent(payPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separatorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelClientCode))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelClientName))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelClientAge))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelClientDate))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainerNIFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTrainerNIF))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNext)
                    .addComponent(buttonBack)
                    .addComponent(buttonFirst)
                    .addComponent(buttonLast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSeePayInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonReturn))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(payPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(79, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonSeePayInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeePayInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSeePayInfoActionPerformed

    private void buttonSeePayInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSeePayInfoMouseClicked

        int codCli = Integer.parseInt(clientCodeTextField.getText());

        changeContent(false);

        String query = "SELECT * FROM MONTHLYPAYMENT WHERE CLIENT_COD = ?";

        ArrayList<Pay> queryResult = new ArrayList();

        queryResult = Querys.queryJList(query, codCli);

        payList.setModel(defLisMod);

        for (Pay p : queryResult) {

            defLisMod.addElement(p);
        }


    }//GEN-LAST:event_buttonSeePayInfoMouseClicked
    DefaultListModel defLisMod = new DefaultListModel();
    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        // TODO add your handling code here:

        payList.setModel(defLisMod);

        defLisMod.clear();

        changeContent(true);

    }//GEN-LAST:event_buttonReturnActionPerformed

    private void buttonReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonReturnMouseClicked
        // TODO add your handling code here:
        changeContent(true);
    }//GEN-LAST:event_buttonReturnMouseClicked

    private boolean notEmptyQuery = false;

    private void buttonNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNextMouseClicked
        // TODO add your handling code here:

        Client c = null;

        if (firstTime) {
            buttonFirst.setVisible(firstTime);
            buttonLast.setVisible(firstTime);
            buttonFirst.setEnabled(firstTime);
            buttonLast.setEnabled(firstTime);
            firstTime = false;
            notEmptyQuery = ClientQuery.executeQuery("SELECT * FROM CLIENT WHERE NID = (SELECT NID FROM TRAINER  WHERE USERNAME = ? AND  PASSWORD = ? ) ORDER BY CLIENT_COD", graphicInterface.getUsername(), graphicInterface.getPassword());
        }

        try {
            checkEmptyQuery();
        } catch (ExceptionError ex) {
            e.emptyQuery(100);
        }

    }//GEN-LAST:event_buttonNextMouseClicked

    private static ExceptionError e = new ExceptionError();

    public void checkEmptyQuery() throws ExceptionError {
        Client c;
        if (notEmptyQuery) {
            buttonSeePayInfo.setEnabled(true);
            c = ClientQuery.moveForward();
            showClientInfo(c);
        } else {

            throw e;
        }
    }

    public void showClientInfo(Client c) {
        clientCodeTextField.setText("" + c.getClientCode());
        clientAgeTextField.setText("" + c.getAge());
        SimpleDateFormat sfd;

        int month = c.getDischargeDate().getMonth() + 1;

        clientDateTextField.setText("" + c.getDischargeDate().getDate() + "-" + month + "-" + c.getDischargeDate().getYear());
        clientNameTextField.setText(c.getFullName());
        trainerNIFTextField.setText(c.getTrainerNID());
    }

    private void buttonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBackMouseClicked
        Client c = null;

        if (notEmptyQuery) {
            c = ClientQuery.moveBackward();
            showClientInfo(c);
        } else {
            e.emptyQuery(100);
        }
    }//GEN-LAST:event_buttonBackMouseClicked

    private void buttonLastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLastMouseClicked

        Client c = null;

        c = ClientQuery.goToEnd();

        showClientInfo(c);


    }//GEN-LAST:event_buttonLastMouseClicked

    private void buttonFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFirstMouseClicked

        Client c = null;

        c = ClientQuery.goToBeginning();

        showClientInfo(c);


    }//GEN-LAST:event_buttonFirstMouseClicked

    public void showClientFields() throws SQLException {
        clientCodeTextField.setText(rs.getString(1));
        clientDateTextField.setText(rs.getString(2));
        clientNameTextField.setText(rs.getString(3));
        clientAgeTextField.setText(rs.getString(4));
        trainerNIFTextField.setText(rs.getString(5));
    }

    static ResultSet rs = null;
    private static boolean firstTime = true;

    public void changeContent(boolean typePanel) {
        // TODO add your handling code here:
        buttonBack.show(typePanel);
        buttonFirst.show(typePanel);
        buttonLast.show(typePanel);
        buttonNext.show(typePanel);
        buttonSeePayInfo.show(typePanel);
        labelClientAge.show(typePanel);
        labelClientName.show(typePanel);
        labelClientCode.show(typePanel);
        labelClientDate.show(typePanel);
        labelTrainerNIF.show(typePanel);
        buttonReturn.show(typePanel);

        if (!typePanel) {
            titleLabel.setText("Payments info");
        } else {
            titleLabel.setText("Query");
        }

        clientCodeTextField.show(typePanel);
        clientAgeTextField.show(typePanel);
        clientNameTextField.show(typePanel);
        clientDateTextField.show(typePanel);
        trainerNIFTextField.show(typePanel);

        if (!typePanel) {
            payPanel.show(true);
            buttonReturn.show(true);
        } else {
            payPanel.show(false);
            buttonReturn.show(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonFirst;
    private javax.swing.JButton buttonLast;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonReturn;
    private javax.swing.JButton buttonSeePayInfo;
    private javax.swing.JTextField clientAgeTextField;
    private javax.swing.JTextField clientCodeTextField;
    private javax.swing.JTextField clientDateTextField;
    private javax.swing.JTextField clientNameTextField;
    private javax.swing.JLabel labelClientAge;
    private javax.swing.JLabel labelClientCode;
    private javax.swing.JLabel labelClientDate;
    private javax.swing.JLabel labelClientName;
    private javax.swing.JLabel labelTrainerNIF;
    private javax.swing.JList<String> payList;
    private javax.swing.JScrollPane payPanel;
    private javax.swing.JSeparator separatorTitle;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField trainerNIFTextField;
    // End of variables declaration//GEN-END:variables

    Color panelBackground = new java.awt.Color(46, 70, 120);
    Color textFieldBackground = new java.awt.Color(129, 143, 173);
    Color buttonBackground = new java.awt.Color(80, 112, 170);

}
